- name: configure Ubuntu
  hosts: ubuntu
  tasks:
    - name: create ssh dir if nonexistent
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        mode: '0700'

    - name: create authorized_keys file
      file:
        path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        state: touch
        mode: '0644'

    - name: copy public key to authorized_keys
      blockinfile:
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        block: "{{ public_key }}"

    - name: create sudoer drop-in file
      file:
        path: "/etc/sudoers.d/480"
        state: touch
        mode: '0440'
      become: yes

    - name: create drop-in entry
      blockinfile:
        dest: "/etc/sudoers.d/480"
        block: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
      become: yes

    - name: set hostname
      hostname:
        name: "{{ hostname }}"
      become: yes

    - name: add host to hosts file
      lineinfile:
        path: "/etc/hosts"
        line: "127.0.1.1 {{ hostname }}"
      become: yes

    - name: Copy netplan template to remote hosts
      template:
        src: Templates/netplan.yml.j2
        dest: /etc/netplan/01-netcfg.yaml
      become: yes

    - name: apply netplan configuration
      command: netplan apply
      become: yes

    - name: bounce the box
      shell: "sleep 5 && shutdown -r"
      become: yes
      async: 1
      poll: 0
