---
- name: vyos DHCP configuration
  hosts: vyos
  gather_facts: no  # Often turned off for network devices to save time unless needed

  tasks:
    - name: Get vyos version
      vyos_command:
        commands: show version
      register: version

    - debug:
        var: version.stdout_lines

    - name: Configure DHCP on VyOS
      vyos_config:
        save: yes
        lines:
          - "set service dhcp-server global-parameters 'local-address {{ hostvars[inventory_hostname].lan_ip }};'"
          - "set service dhcp-server shared-network-name {{ hostvars[inventory_hostname].shared_network }} authoritative"
          - "set service dhcp-server shared-network-name {{ hostvars[inventory_hostname].shared_network }} subnet {{ hostvars[inventory_hostname].lan }} default-router '{{ hostvars[inventory_hostname].lan_ip }}'"
          - "set service dhcp-server shared-network-name {{ hostvars[inventory_hostname].shared_network }} subnet {{ hostvars[inventory_hostname].lan }} name-server '{{ hostvars[inventory_hostname].dhcp_name_server }}'"
          - "set service dhcp-server shared-network-name {{ hostvars[inventory_hostname].shared_network }} subnet {{ hostvars[inventory_hostname].lan }} domain-name '{{ hostvars[inventory_hostname].dhcp_domain }}'"
          - "set service dhcp-server shared-network-name {{ hostvars[inventory_hostname].shared_network }} subnet {{ hostvars[inventory_hostname].lan }} lease '86400'"
          - "set service dhcp-server shared-network-name {{ hostvars[inventory_hostname].shared_network }} subnet {{ hostvars[inventory_hostname].lan }} range {{ hostvars[inventory_hostname].shared_network }}-POOL start '10.0.5.75'"
          - "set service dhcp-server shared-network-name {{ hostvars[inventory_hostname].shared_network }} subnet {{ hostvars[inventory_hostname].lan }} range {{ hostvars[inventory_hostname].shared_network }}-POOL stop '10.0.5.125'"
